detection: 0
track: 1
engine: "/space/model/visdrone-8s-2c-1011.engine"
videopath: "/space/data/pl/IMG_3570.MOV"
# engine: "/home/nx/model/vis-8s-2c.engine"
# videopath: "/home/nx/data/IMG_3573-ok.MOV"
# videopath: "/home/nx/data/day_truck_track_lost.mp4"