
    network:
        version: 2
        renderer: networkd
        ethernets:
            enP3p49s0:
                dhcp4: no
                addresses: [192.168.4.164/24]
                gateway4: 192.168.4.1
                nameservers:
                    addresses: [8.8.8.8,8.8.4.4]
    